language: r
sudo: required

warnings_are_errors: TRUE

r_packages:
  - covr

r_binary_packages:
  - rstan
  - ggplot2
  - testthat
  
after_success:
  - Rscript -e 'library(covr); codecov()'
  
cran: https://cran.rstudio.com  