language: r
r: devel
sudo: FALSE
cache: packages

warnings_are_errors: TRUE

r_github_packages:
  - jimhester/covr
  - stan-dev/rstantools
  - stan-dev/rstan/rstan/rstan@develop
  
after_success:
  - Rscript -e 'covr::codecov()'
