language: r
r: devel
sudo: false
cache: packages

warnings_are_errors: TRUE

r_github_packages:
  - jimhester/covr
  - hadley/ggplot2
  - stan-dev/rstan/rstan/rstan@develop
  - stan-dev/bayesplot
  
after_success:
  - Rscript -e 'covr::codecov()'
